// Lucas Cavalcante — https://github.com/Luqetaa
export const projectsData = [
  {
    id: 1,
    title: "Marathon Portfolio",
    category: "Web Application",
    year: "2026",
    description: "Portfolio pessoal com estética de game HUD — Three.js, animações e tema dinâmico.",
    longDescription: "Portfolio de alta performance construído com React, Tailwind CSS e Framer Motion. Possui background de partículas Three.js, cursor customizado com brackets, boot screen terminal, sistema de temas dinâmico e scroll contínuo sem travada — tudo inspirado em interfaces de jogos AAA.",
    tags: ["React", "Tailwind", "Framer Motion", "Three.js"],
    image: "https://opengraph.githubassets.com/1/Luqetaa/portfolio",
    link: "https://github.com/Luqetaa/portfolio",
    github: "https://github.com/Luqetaa/portfolio",
    demo: "#",
    status: "IN PROGRESS",
    featured: true,
  },
  {
    id: 2,
    title: "Skill Sync App",
    category: "Web Application",
    year: "2025",
    description: "Plataforma de sincronização de habilidades desenvolvida em JavaScript.",
    longDescription: "Aplicação web completa para gerenciamento e sincronização de habilidades. Construída com JavaScript moderno, permite que usuários cataloguem e acompanhem seu desenvolvimento profissional de forma visual e interativa.",
    tags: ["JavaScript", "React", "Vercel"],
    image: "https://opengraph.githubassets.com/1/Luqetaa/skill-sync-app",
    link: "https://skill-sync-app-black.vercel.app",
    github: "https://github.com/Luqetaa/skill-sync-app",
    demo: "https://skill-sync-app-black.vercel.app",
    status: "DEPLOYED",
    featured: true,
  },
  {
    id: 3,
    title: "Passa a Bola",
    category: "MVP",
    year: "2025",
    description: "Organizador de campeonatos de futebol feminino com React e Vite.",
    longDescription: "MVP do organizador de campeonatos de futebol feminino do 'Passa a Bola'. Desenvolvido com React, Vite e Tailwind CSS. Permite cadastro de times, geração de chaves e acompanhamento de resultados em tempo real.",
    tags: ["React", "Vite", "Tailwind"],
    image: "https://opengraph.githubassets.com/1/Luqetaa/passa-a-bola-web-app-sprint-4-",
    link: "https://passa-a-bola-web-app-sprint-4.vercel.app",
    github: "https://github.com/Luqetaa/passa-a-bola-web-app-sprint-4-",
    demo: "https://passa-a-bola-web-app-sprint-4.vercel.app",
    status: "DEPLOYED",
    featured: false,
  },
  {
    id: 4,
    title: "GS Edge — IoT",
    category: "IoT / Embarcados",
    year: "2025",
    description: "Medidor de velocidade e sensor IoT com C++ e Arduino para Global Solution.",
    longDescription: "Projeto de IoT desenvolvido em C++ com Arduino/ESP para a Global Solution da FIAP. Implementa sensores de velocidade, coleta de dados em tempo real e transmissão via protocolo serial.",
    tags: ["C++", "Arduino", "IoT"],
    image: "https://opengraph.githubassets.com/1/Luqetaa/GS-edge",
    link: "https://github.com/Luqetaa/GS-edge",
    github: "https://github.com/Luqetaa/GS-edge",
    demo: null,
    status: "DEPLOYED",
    featured: false,
  },
];


export const skillsData = {
  "Frontend": ["React", "Vite", "Tailwind CSS", "Framer Motion", "HTML", "CSS"],
  "Backend": ["Node.js", "Express", "REST APIs", "PostgreSQL", "MongoDB"],
  "IoT / Embarcados": ["C++", "Arduino", "ESP32", "Sensores", "Protocolos Serial"],
  "Ferramentas": ["Git", "GitHub", "VS Code", "Figma", "Vercel"],
  "Estudando": ["TypeScript", "Next.js", "Docker", "Estruturas de Dados"],
};

export const statusColors = {
  "DEPLOYED": "#00ff00",
  "IN PROGRESS": "#ffff00",
  "RESEARCH": "#00ccff",
};
